# Generated by Django 3.0.11 on 2020-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column', '0002_auto_20201227_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcolumntype',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
