# Generated by Django 3.0.11 on 2021-01-09 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_provider', '0001_initial'),
        ('custom_column', '0003_customcolumntype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColumnTypeValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_column_customcolumntypevalidator_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('custom_column_config_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_column.CustomColumnConfigValidation')),
                ('custom_column_regex_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_column.CustomColumnRegexType')),
            ],
            options={
                'db_table': 'custom_column_type_validator',
            },
        ),
        migrations.RemoveField(
            model_name='customcolumnconfigtypevalidator',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='customcolumnconfigtypevalidator',
            name='custom_column_config_type',
        ),
        migrations.RemoveField(
            model_name='customcolumnconfigtypevalidator',
            name='custom_column_config_validation',
        ),
        migrations.RemoveField(
            model_name='customcolumnconfigtypevalidator',
            name='custom_column_regex_type',
        ),
        migrations.RemoveField(
            model_name='customcolumnconfigtypevalidator',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='customcolumntype',
            name='custom_column_config_type',
        ),
        migrations.AddField(
            model_name='customcolumntype',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_provider.DBProviderConnection'),
        ),
        migrations.DeleteModel(
            name='CustomColumnConfigType',
        ),
        migrations.DeleteModel(
            name='CustomColumnConfigTypeValidator',
        ),
        migrations.AddField(
            model_name='customcolumntypevalidator',
            name='custom_column_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_column.CustomColumnType'),
        ),
        migrations.AddField(
            model_name='customcolumntypevalidator',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_column_customcolumntypevalidator_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
    ]
