# Generated by Django 3.0.11 on 2021-01-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_provider', '0001_initial'),
        ('custom_column', '0004_auto_20210109_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColumnMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('real_column', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_provider.DBProviderConnection')),
                ('custom_column_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_column.CustomColumnType')),
            ],
            options={
                'db_table': 'custom_column_mapping',
            },
        ),
    ]
