# Generated by Django 3.0.11 on 2021-01-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column', '0005_customcolumnmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcolumnmapping',
            old_name='custom_column_id',
            new_name='custom_column',
        ),
    ]
