# Generated by Django 3.0.11 on 2021-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column', '0007_customcolumntaskconvert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customcolumntaskconvert',
            table='custom_column_task_convert',
        ),
    ]
