# Generated by Django 3.0.11 on 2021-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column', '0008_auto_20210114_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcolumnconfigvalidation',
            name='custom_column_regex_type',
        ),
        migrations.RemoveField(
            model_name='customcolumntypevalidator',
            name='custom_column_regex_type',
        ),
        migrations.AddField(
            model_name='customcolumnconfigvalidation',
            name='is_regex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customcolumnconfigvalidation',
            name='regex',
            field=models.CharField(blank=True, choices=[('is_number', 'Is Number'), ('is_text_only', 'Is Text Only'), ('is_email', 'Is Email'), ('is_phone', 'Is Phone'), ('is_custom', 'Is Custom')], default=None, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='CustomColumnRegexType',
        ),
    ]
