# Generated by Django 3.0.11 on 2021-01-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column', '0010_customcolumntypevalidator_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcolumntypevalidator',
            name='custom_column_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_column_type_validations', to='custom_column.CustomColumnType'),
        ),
    ]
