# Generated by Django 3.0.11 on 2021-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column_fk', '0002_customcolumnfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcolumnfk',
            name='operator',
            field=models.CharField(blank=True, choices=[('in', 'in'), ('not_in', 'not in'), ('contains', 'regex'), ('equals', '='), ('not_equals', '!='), ('less_than', '<'), ('less_than_or_equals', '<='), ('greater_than', '>'), ('less_greater_than_or_equals', '>=')], default='equals', max_length=32, null=True),
        ),
    ]
