# Generated by Django 3.0.11 on 2021-01-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_column_fk', '0004_auto_20210114_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcolumnfkfilter',
            name='custom_column_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_column_fk_filters', to='custom_column_fk.CustomColumnFK'),
        ),
    ]
