# Generated by Django 3.0.11 on 2020-12-28 16:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import wab.utils.jsonb


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(
                    choices=[('email', 'Email channel'), ('push_notification', 'Push notification channel')],
                    default='email', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('template', models.TextField(blank=True)),
                ('config', wab.utils.jsonb.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'notify_channel',
            },
        ),
        migrations.CreateModel(
            name='NotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'notify_user',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('contact',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True,
                                                           default=list, null=True, size=None)),
                ('app', models.CharField(default='HAPPY', max_length=64)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.NotifyUser')),
            ],
            options={
                'db_table': 'notify_subscribe',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('init', 'init'), ('sending', 'sending'), ('sent', 'send'), ('read', 'read'),
                             ('pending', 'pending'), ('rejected', 'rejected')], default='init', max_length=64)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('data', wab.utils.jsonb.JSONField(blank=True, null=True)),
                ('response', wab.utils.jsonb.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='notifications.Channel')),
                ('user', models.ManyToManyField(blank=True, null=True, to='notifications.NotifyUser')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
