# Generated by Django 3.0.11 on 2021-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ManyToManyField(blank=True, to='notifications.NotifyUser'),
        ),
    ]
