# Generated by Django 3.0.11 on 2020-12-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='db_provider.DBProviderConnection')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='sql_function_sqlfunction_creator',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='sql_function_sqlfunction_last_modified', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last modified by')),
            ],
            options={
                'db_table': 'sql_function',
            },
        ),
        migrations.CreateModel(
            name='SqlFunctionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='sql_function_sqlfunctioncondition_creator',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='sql_function_sqlfunctioncondition_last_modified',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('sql_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='sql_function.SqlFunction')),
            ],
            options={
                'db_table': 'sql_function_condition',
            },
        ),
        migrations.CreateModel(
            name='SqlFunctionOrderBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('order_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='sql_function_sqlfunctionorderby_creator',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='sql_function_sqlfunctionorderby_last_modified',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('sql_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='sql_function.SqlFunction')),
            ],
            options={
                'db_table': 'sql_function_order_by',
            },
        ),
        migrations.CreateModel(
            name='SqlFunctionMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('merge_type', models.CharField(
                    choices=[('inner_join', 'inner join'), ('left_join', 'left join'), ('right_join', 'right join'),
                             ('right_outer_join', 'right outer join'), ('union', 'union')], default='inner_join',
                    max_length=32)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='sql_function_sqlfunctionmerge_creator',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='sql_function_sqlfunctionmerge_last_modified',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('sql_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='sql_function.SqlFunction')),
            ],
            options={
                'db_table': 'sql_function_merge',
            },
        ),
        migrations.CreateModel(
            name='SqlFunctionConditionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operator',
                 models.CharField(choices=[('type_equal', '='), ('type_in', 'in'), ('type_contain', 'contain')],
                                  default='type_equal', max_length=32)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('relation',
                 models.CharField(choices=[('relation_and', 'and'), ('relation_or', 'or')], default='relation_and',
                                  max_length=32)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='sql_function_sqlfunctionconditionitems_creator',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='sql_function_sqlfunctionconditionitems_last_modified',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('sql_function_condition',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='sql_function.SqlFunctionCondition')),
            ],
            options={
                'db_table': 'sql_function_condition_items',
            },
        ),
    ]
