# Generated by Django 3.0.11 on 2021-01-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_function', '0002_auto_20201227_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlfunctionconditionitems',
            name='sql_function_condition',
        ),
        migrations.AddField(
            model_name='sqlfunctionconditionitems',
            name='sql_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sql_function.SqlFunction'),
        ),
        migrations.AddField(
            model_name='sqlfunctionmerge',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sqlfunctionconditionitems',
            name='operator',
            field=models.CharField(blank=True, choices=[('in', 'in'), ('not_in', 'not in'), ('contains', 'regex'), ('equals', '='), ('not_equals', '!='), ('less_than', '<'), ('less_than_or_equals', '<='), ('greater_than', '>'), ('less_greater_than_or_equals', '>=')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sqlfunctionmerge',
            name='merge_type',
            field=models.CharField(blank=True, choices=[('inner join', 'inner join'), ('left join', 'left join'), ('right join', 'right join'), ('right outer join', 'right outer join'), ('union', 'union')], default=None, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='SqlFunctionCondition',
        ),
    ]
