# Generated by Django 3.0.11 on 2021-01-03 11:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import wab.utils.jsonb


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('table', models.CharField(blank=True, max_length=128, null=True)),
                ('record', django.contrib.postgres.fields.ArrayField(base_field=wab.utils.jsonb.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_provider.DBProviderConnection')),
            ],
            options={
                'db_table': 'import_data',
            },
        ),
    ]
