# Generated by Django 3.0.11 on 2021-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdata',
            name='record',
        ),
        migrations.AddField(
            model_name='importdata',
            name='file_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
